# Numpy- Numerical Python
   - Numpy is an array
   - Numpy is for faster array operations
   - Vectorzed operation (no loop involves in iteration)

In [62]:
import numpy as np

# creating numpy arrays

#### passging a python list to numpy array

In [63]:
lst = [1,2,3,4,5,6,7,8,9,10]
type(lst)

list

In [64]:
arr = np.array(lst)
type(arr)

numpy.ndarray

In [65]:
arr.size

10

In [66]:
arr.shape

(10,)

In [67]:
arr.ndim

1

In [68]:
arr2d = np.array([[1,2,3],[3,2,1],[4,5,6],[7,8,9],[8,7,6]])

In [69]:
arr2d.size

15

In [70]:
arr2d.shape

(5, 3)

In [71]:
arr2d.ndim

2

#### using numpy arange

In [72]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### using numpy random

In [73]:
arr1d = np.random.randn(10)
arr1d

array([-1.13411932, -0.29297222,  0.61763376,  0.33802154,  0.12615723,
        0.37804251, -1.0316374 , -0.92970891,  0.19652416,  0.44295727])

In [74]:
arr2d = np.random.randn(4,6)

In [75]:
print(arr2d)

[[ 0.50468655 -0.87781733 -0.05749396  0.15381488  0.75796449 -0.91660443]
 [-0.13979597 -0.89342517  0.49509243  1.50142373 -0.08456121 -0.72320871]
 [-0.81815136 -0.3993665  -1.52930253 -0.53754469  1.26215178  0.49267655]
 [-0.92992527  0.31523392 -0.21098867 -1.18634183 -1.67923862  0.54621424]]


In [76]:
arr0d

NameError: name 'arr0d' is not defined

In [ ]:
arr3d = np.arange(64).reshape(4,4,4)

In [77]:
arr3d

NameError: name 'arr3d' is not defined

In [ ]:
from PIL import Image

In [78]:
image = Image.open('pic.jpeg')

NameError: name 'Image' is not defined

In [ ]:
image

In [79]:
print(image.format)
print(image.size)
print(image.mode)

NameError: name 'image' is not defined

In [ ]:
np_img = np.array(image)

In [80]:
np_img

NameError: name 'np_img' is not defined

In [ ]:
arr1d = np.arange(10)
arr1d

In [81]:
arr2d = np.arange(16).reshape(4,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
arr2d = np.arange(16).reshape(2,8)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [83]:
arr2d = np.arange(16).reshape(8,2)
arr2d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [84]:
arr2d = np.arange(16).reshape(1,16)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [85]:
arr2d = np.arange(16).reshape(16,1)
arr2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [86]:
arr2d = np.arange(16).reshape(2,16)
arr2d

ValueError: cannot reshape array of size 16 into shape (2,16)

In [ ]:
arr2d = np.arange(1,37).reshape(6,6)
arr2d

In [87]:
arr2d.max()

np.int64(15)

In [88]:
arr2d.min()

np.int64(0)

In [89]:
arr2d.mean()

np.float64(7.5)

In [90]:
arr2d.argmax()

np.int64(15)

In [91]:
arr2d.argmin()

np.int64(0)

# indexing and slicing numpy arrray

In [92]:
arr2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [93]:
arr2d[1:5,1:5]

array([], shape=(4, 0), dtype=int64)

In [94]:
arr2d[1:2,1:5]

array([], shape=(1, 0), dtype=int64)

In [95]:
arr2d[3,3]

IndexError: index 3 is out of bounds for axis 1 with size 1

In [ ]:
arr2d[4,1]

In [96]:
arr2d[0,1]

IndexError: index 1 is out of bounds for axis 1 with size 1

# arr2d[sr:er , sc:ed]

In [97]:
arr2d[2:4,1:5]

array([], shape=(2, 0), dtype=int64)

In [98]:
arr2d[3:4,3:4 ]

array([], shape=(1, 0), dtype=int64)

In [99]:
arr2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [100]:
arr2d[3,3:5]

array([], dtype=int64)

In [101]:
arr2d[:,4 ]

IndexError: index 4 is out of bounds for axis 1 with size 1

In [ ]:
arr2d[:,4:5 ]

# Vecotrized Operation`

In [102]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
[e*4 for e in arr]

[np.int64(4),
 np.int64(8),
 np.int64(12),
 np.int64(16),
 np.int64(20),
 np.int64(24),
 np.int64(28),
 np.int64(32),
 np.int64(36),
 np.int64(40)]

In [104]:
lst=[]
for a in arr:
    lst.append(a*4)
lst

[np.int64(4),
 np.int64(8),
 np.int64(12),
 np.int64(16),
 np.int64(20),
 np.int64(24),
 np.int64(28),
 np.int64(32),
 np.int64(36),
 np.int64(40)]

In [105]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
arr*4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [107]:
arr2d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [108]:
arr2d2 = arr2d*10

# Arithmetic Operation

In [109]:
arr2d + arr2d2

array([[  0],
       [ 11],
       [ 22],
       [ 33],
       [ 44],
       [ 55],
       [ 66],
       [ 77],
       [ 88],
       [ 99],
       [110],
       [121],
       [132],
       [143],
       [154],
       [165]])

In [110]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,5,6,4])

In [111]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [ ]:
arr3 = np.arange(20,26)
arr3

In [112]:
arr2

array([1, 2, 3, 5, 6, 4])

In [113]:
arr3 * arr2

array([ 20,  42,  66, 115, 144, 100])

In [114]:
arr2d1= np.arange(24).reshape(6,4)
arr2d2 = np.arange(24,48).reshape(4,6)

In [115]:
arr2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [116]:
arr2d2

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [117]:
arr2d1 * arr2d2

ValueError: operands could not be broadcast together with shapes (6,4) (4,6) 

In [ ]:
arr2d1@arr2d2

In [118]:
arr2d1.dot(arr2d2)

array([[ 228,  234,  240,  246,  252,  258],
       [ 756,  778,  800,  822,  844,  866],
       [1284, 1322, 1360, 1398, 1436, 1474],
       [1812, 1866, 1920, 1974, 2028, 2082],
       [2340, 2410, 2480, 2550, 2620, 2690],
       [2868, 2954, 3040, 3126, 3212, 3298]])